Log:
  Level: error
  Color: true
  JSON: false

API:
  HTTP:
    Port: 8080

PostgreSQL:
  DBHost: 'localhost'
  DBPort: '5433'
  DBUsername: 'postgres'
  DBPassword: 'postgres'
  DBName: 'simple_core_bank'
  DBSchemaName: 'public'
  MaxOpenConns: 30
