Log:
  Level: debug
  Color: true
  JSON: false

API:
  HTTP:
    Port: 8080

PostgreSQL:
  DBHost: 'postgres'
  DBPort: '5432'
  DBUsername: 'postgres'
  DBPassword: 'postgres'
  DBName: 'simple_core_bank'
  DBSchemaName: 'public'
  MaxOpenConns: 30
