Log:
  Level: debug
  Color: true
  JSON: false

API:
  HTTP:
    Port: 8080

Database:
  Type: "postgres"
  PostgreSQL:
    Type: "postgres"
    DBHost: 'localhost'
    DBPort: '5432'
    DBUsername: 'postgres'
    DBPassword: 'postgres'
    DBName: 'go-http-server-template'
    DBSchemaName: 'public'
    MaxOpenConns: 30
