version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    user: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-go-http-server-template}
      TZ: Asia/Bangkok
    ports:
      - '5432:5432'
    networks:
      -  go-http-server-template-network
    restart: always
    healthcheck:
      test: pg_isready
      interval: 5s
      timeout: 5s
      retries: 5

  go-http-server-template:
    image: go-http-server-template
    container_name: go-http-server-template
    build: .
    volumes:
      - ./cfg/config.docker.yaml:/cfg/config.yaml:ro
    environment:
      TZ: Asia/Bangkok
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    entrypoint:
      [
        'make',
        'run-without-build'
      ]
    networks:
      - go-http-server-template-network

networks:
  go-http-server-template-network:
    driver: bridge